services:
  backend:
    build:
      args:
        - target=dev
    environment:
      GO_ENV: dev
      PORT: 8080
    ports:
      - 18000:8000
    volumes:
      - .:/app
    command: sh -c 'go mod tidy && air'