services:
  backend:
    container_name: go-backend-APP
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    container_name: go-backend-DB
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABSE: shop_site
      MYSQL_USER: gof1ber
      MYSQL_PASSWORD: gof1ber
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  redis:
    image: redis:7.0
    ports:
      - 6379:6379